identifier: lbd9ban0dbb32ed3
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: elewa-group-website
homeFolder: /Users/jrosseel/Documents/GitHub/elewa-group-2
distFolder: ./dist/apps/elewa-group-website
outDir: /Users/jrosseel/Documents/GitHub/elewa-group-2/dist/static
handle404: ''
allowErrorCollect: false
